# Generated by Django 3.2.4 on 2021-08-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagerelated',
            options={'ordering': ['id'], 'verbose_name': 'ImageRelated', 'verbose_name_plural': 'ImageRelated'},
        ),
    ]
