# Generated by Django 3.2.4 on 2021-08-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginrecord_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginrecord',
            name='is_valid',
        ),
    ]
