# Generated by Django 3.2.4 on 2021-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210819_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=13000000000, max_length=20, verbose_name='phone number'),
        ),
    ]
