# Generated by Django 3.2.4 on 2021-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210820_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='username',
            field=models.CharField(editable=False, max_length=150, verbose_name='username'),
        ),
    ]
