# Generated by Django 3.2.4 on 2021-08-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_loginrecord_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='source',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='version',
        ),
    ]
