# Generated by Django 3.2.4 on 2021-09-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210913_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, unique=True, verbose_name='nickname'),
        ),
    ]
