# Generated by Django 3.2.4 on 2021-09-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'verbose_name': '用户登录历史', 'verbose_name_plural': '用户登录历史'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户详细信息', 'verbose_name_plural': '用户详细信息'},
        ),
    ]
