# Generated by Django 3.2.4 on 2021-08-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sightticket',
            options={'ordering': ['id'], 'verbose_name': 'SightTicket', 'verbose_name_plural': 'SightTicket'},
        ),
    ]
