# Generated by Django 3.2.4 on 2021-09-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0002_alter_sightticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightticket',
            name='remark',
        ),
    ]
