# Generated by Django 3.2.4 on 2021-09-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0003_remove_sightticket_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightticket',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
    ]
