# Generated by Django 3.2.4 on 2021-09-02 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='if is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='order no')),
                ('buy_count', models.IntegerField(default=1, verbose_name='buy count')),
                ('buy_amount', models.FloatField(verbose_name='buy amount')),
                ('to_user', models.CharField(max_length=32, verbose_name='receiver')),
                ('to_area', models.CharField(default='', max_length=64, verbose_name='area')),
                ('to_address', models.CharField(default='', max_length=128, verbose_name='detail address')),
                ('to_phone', models.CharField(max_length=128, verbose_name='detail address')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='remark')),
                ('express_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='express type')),
                ('express_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='express no')),
                ('types', models.SmallIntegerField(choices=[(10, '门票'), (11, '酒店')], default=10, verbose_name='order type')),
                ('status', models.SmallIntegerField(choices=[(11, '待支付'), (12, '已支付'), (13, '已取消')], default=11, verbose_name='order status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_list', to=settings.AUTH_USER_MODEL, verbose_name='User related')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'db_table': 'Order',
                'ordering': ['id'],
            },
        ),
    ]
