# Generated by Django 3.2.4 on 2021-09-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='if is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('flash_name', models.CharField(max_length=128, verbose_name='flash name')),
                ('flash_img', models.ImageField(max_length=512, upload_to='order/%Y%m', verbose_name='flash img')),
                ('flash_origin_price', models.FloatField(verbose_name='flash origin price')),
                ('flash_price', models.FloatField(verbose_name='flash price')),
                ('flash_discount', models.FloatField(default=10.0, verbose_name='flash discount')),
                ('buy_count', models.IntegerField(default=1, verbose_name='buy count')),
                ('buy_amount', models.FloatField(verbose_name='buy amount')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='remark')),
                ('status', models.SmallIntegerField(choices=[(11, '待支付'), (12, '已支付'), (13, '已取消')], default=11, verbose_name='order status')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='model related')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_list', to='order.order', verbose_name='Order related')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_list', to=settings.AUTH_USER_MODEL, verbose_name='User related')),
            ],
            options={
                'verbose_name': 'Order_item',
                'verbose_name_plural': 'Order_item',
                'db_table': 'Order_item',
                'ordering': ['id'],
            },
        ),
    ]
