# Generated by Django 3.2.4 on 2021-09-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='if is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.FloatField(help_text='real pay', verbose_name='amount')),
                ('pay_sn', models.CharField(max_length=32, verbose_name='pay no')),
                ('third_sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='third pay sn')),
                ('status', models.SmallIntegerField(choices=[(11, '待支付'), (12, '已支付'), (13, '已取消')], default=11, verbose_name='pay status')),
                ('meta', models.CharField(blank=True, max_length=128, null=True, verbose_name='meta')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='remark')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_list', to='order.order', verbose_name='Order related')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_list', to=settings.AUTH_USER_MODEL, verbose_name='User related')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
                'db_table': 'Order_payment',
                'ordering': ['id'],
            },
        ),
    ]
