# Generated by Django 3.2.4 on 2021-09-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_phone',
            field=models.CharField(max_length=128, verbose_name='手机号'),
        ),
    ]
